num = int(input ("Enter a n(1-3999): "))
roman = 'M' * (num // 1000)
roman += 'C' * (num % 1000 // 100)
roman += 'X' * (num % 100 // 10)
roman += 'I' * (num % 10 // 1)
roman = roman.replace ('C' * 9 , 'CM')
roman = roman.replace ('C' * 5 , 'D')
roman = roman.replace ('C' * 4 , 'CD')
roman = roman.replace ('X' * 9 , 'XC')
roman = roman.replace ('X' * 5 , 'L')
roman = roman.replace ('X' * 4 , 'XL')
roman = roman.replace ('I' * 9 , 'IX')
roman = roman.replace ('I' * 5 , 'V')
roman = roman.replace ('I' * 4 , 'IV')
print (roman)
